# Generated by Django 4.2.30 on 2026-05-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_resume', models.JSONField(default=dict, help_text='Full resume as structured JSON (work, education, projects, etc.)')),
                ('skills', models.JSONField(default=list, help_text="Flat list of skill strings, e.g. ['Python', 'Django', 'SQL']")),
                ('prefs', models.JSONField(default=dict, help_text="Job search preferences: {'regions': [...], 'keywords': [...], 'salary_floor': 0}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
