# Generated by Django 6.0.5 on 2026-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filterpreset_ingestrun_job_resumeversion_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='region_override',
            field=models.CharField(blank=True, help_text='Set manually to override inferred region', max_length=64),
        ),
    ]
