# Generated by Django 6.0.5 on 2026-05-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_region_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
    ]
