# Generated by Django 6.0.5 on 2026-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resumeversion_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latex_source',
            field=models.TextField(blank=True, help_text='Hand-edited LaTeX. When set, it overrides the generated .tex for the base resume.'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='latex_source',
            field=models.TextField(blank=True, help_text='Hand-edited LaTeX. When set, it overrides the generated .tex for this version.'),
        ),
    ]
