# Generated by Django 6.0.5 on 2026-05-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_latex_source_resumeversion_latex_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='semantic_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
