# Generated by Django 6.0.5 on 2026-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_duplicate_of_job_embedding_job_is_duplicate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestrun',
            name='gone_count',
            field=models.IntegerField(default=0),
        ),
    ]
