# Generated by Django 6.0.5 on 2026-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ingestrun_gone_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='screening_answers',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer} drafts for application screening questions.'),
        ),
    ]
