# Generated by Django 6.0.5 on 2026-05-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_resumeversion_screening_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='followup_draft',
            field=models.TextField(blank=True, help_text='Drafted follow-up email (you send it).'),
        ),
    ]
